//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapReduce.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scipts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scipts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapReduce.Tests.Scipts", typeof(Scipts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function() {
        ///    var getDate = function(year, month, day, hours, minutes)
        ///    {
        ///      var date = new Date(0);
        ///      date.setUTCFullYear(year);	
        ///      date.setUTCMonth(month - 1);	
        ///      date.setUTCDate(day);
        ///      date.setUTCHours(hours);
        ///      date.setUTCMinutes(minutes);
        ///      return date;
        ///    };
        ///    
        ///    var startDate = getDate(2011, 1, 1, 15, 0);
        ///    var endDate = getDate(2011, 1, 5, 0, 0);
        ///    
        ///    if(this.StartDate &lt; endDate &amp;&amp; this.EndDate &gt; startDate)
        ///    {
        ///      var delta = 300000; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function(key, values) {
        ///    // print(&apos;reduce - startDate: &apos; + key.startDate + &apos; endDate: &apos; + key.endDate);
        ///    // print(&apos;values: &apos; + values.length);
        ///    // print(&apos;---------------------------&apos;);
        ///    return values.length;
        ///  };.
        /// </summary>
        internal static string reduce {
            get {
                return ResourceManager.GetString("reduce", resourceCulture);
            }
        }
    }
}
